config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'confirm_application', on: :member
  end
  resources :beer_clubs
  resources :users do 
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'signup', to: 'users#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'
  #get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signin', to: 'sessions#new'
  #get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user

  has_many :confirmed_memberships, -> { where(confirmed: true) },
           class_name: "Membership"

  has_many :confirmed_members, through: :confirmed_memberships, source: :user

  has_many :applied_memberships, -> { where(confirmed: [nil, false]) },
           class_name: "Membership"

  has_many :applied_members, through: :applied_memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[show edit update destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "city" then @beer_clubs.sort_by(&:city)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @membership.user = current_user
    @confirmed_members = @beer_club.confirmed_members
    @applied_memberships = @beer_club.applied_memberships

    return unless current_user.present?

    return unless current_user.beer_clubs.exists?(@beer_club.id)

    @membership = Membership.find_by(user_id: current_user.id, beer_club_id: @beer_club.id)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        current_user.memberships.create(beer_club: @beer_club, confirmed: true)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <h2>
    <%= beer_club.name %>
  </h2>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

  <h4>members</h4>

  <% @confirmed_members.each do |member| %>
    <p>
      <%= link_to member.username, member %>
    </p>
  <% end %>

  <h4>membership applications</h4>

  <% @applied_memberships.each do |membership| %>
    <p>
      <%= link_to membership.user.username, membership.user %> (Waiting for confirmation)
      <% if not current_user == membership.user %>
        <%= link_to "confirm", confirm_application_membership_path(membership), data: {turbo_method: "post"}, class: "btn btn-primary" %>
      <% end %>
    </p>
  <% end %>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, class: "form") do |form| %>
  <% if beer_club.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :founded, class: "form-label" %>
    <%= form.number_field :founded, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :city, class: "form-label" %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
<table class="table table-striped  table-hover">
  <thead>
    <tr>
      <th><%= link_to "Name", beer_clubs_path(order: "name")%></th>
      <th><%= link_to "City", beer_clubs_path(order: "city")%></th>
      <th><%= link_to "Year", beer_clubs_path(order: "founded")%></th>
    </tr>
  </thead>
  <% @beer_clubs.each do |beer_club| %>
    <tr>
      <td><%= link_to beer_club.name, beer_club %></td>
      <td><%= beer_club.city %></td>
      <td><%= beer_club.founded %></td>
    </tr>
  <% end %>
</table>
</div>

<%= link_to "New beer club", new_beer_club_path, class:'btn btn-primary' %>

app/views/beer_clubs/new.html.erb
<h1>New beerclub</h1>

<%= render "form", beer_club: @beer_club %>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<% if current_user %>
<% if current_user.memberships.map{ |m| m.beer_club_id }.exclude?(@beer_club.id) %>
  <div>
    <%= form_with(model: @membership) do |form| %>
    <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "Join the beer club" %>
  </div>
  <% end %>
<% else %>
  <%= form_with(model: @membership, method: :delete) do |form| %>
    <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "End the membership" %>
  <% end %>
<% end %>

  <%= link_to "Edit this beer club", edit_beer_club_path(@beer_club) %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
  <%= button_to "Destroy this beer club", @beer_club, method: :delete %>
<% end %>