config/routes.rb
Rails.application.routes.draw do
  resources :memberships do
    post 'confirm_application', on: :member
  end
  resources :beer_clubs
  resources :users do 
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'signup', to: 'users#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'
  #get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signin', to: 'sessions#new'
  #get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  delete 'signout', to: 'sessions#destroy'
  resources :ratings, only: [:index, :new, :create]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage
  extend Top

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1040 }
  validate :year_cannot_be_in_the_future

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def year_cannot_be_in_the_future
    return unless year > Time.now.year

    errors.add(:year, "year cannot be in the future!")
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_adminuser, only: %i[destroy]

  # GET /breweries or /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  def list
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2>
    <%= brewery.name %>
    <% if not brewery.active  %>
      <span class="badge bg-secondary">retired</span>
    <% end %>
  </h2>

  <p>
    <i>
      Established in
      <%= brewery.year %>
    </i>
  </p>

  <p>
  Number of beers: 
  <%= @brewery.beers.count %>
  </p>

  <p>
  <% brewery.beers.each do |beer| %>
    <%= link_to beer.name, beer %>
  <% end %>
 </p>

  <p>
    <% if not brewery.ratings.empty? %>
      Brewery has <%= pluralize(brewery.ratings.count, "rating") %> with average of <%= brewery.average_rating %>
    <% end %>
  </p>
</div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
  <%= form.label :active, style: "display: block" %>
  <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery, class:'btn btn-primary' %>
  <%= link_to "Back to breweries", breweries_path, class:'btn btn-primary' %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<h3>Active</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Established in</th>
      <th>Number of Beers</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @active_breweries.each do |brewery| %>
      <tr id="<%= dom_id brewery %>">
        <td>
          <%= link_to brewery.name, brewery %>
        </td>
        <td>
          <%= brewery.year %>
        </td>
        <td>
          <%= brewery.beers.count %>
        </td>
        <td>
          <%= brewery.average_rating %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<h3>Retired</h3>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Established in</th>
      <th>Number of Beers</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @retired_breweries.each do |brewery| %>
      <tr id="<%= dom_id brewery %>">
        <td>
          <%= link_to brewery.name, brewery %>
        </td>
        <td>
          <%= brewery.year %>
        </td>
        <td>
          <%= brewery.beers.count %>
        </td>
        <td>
          <%= brewery.average_rating %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<%= link_to('New Brewery', new_brewery_path, class:'btn btn-primary') if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th> <span id="name">Name</span> </th>
      <th> <span id="year">Year</span> </th>
      <th> <span id="beers">Beers</span> </th>
      <th> <span id="active">Active</span> </th>
    </tr>
  <thead>
  <tbody>
    <div id="brewerylist"></div>
  </tbody>
</table>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/show.html.erb
<%= render @brewery %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: {turbo_method: "post"}, class: "btn btn-primary" %>
<p></p>
<div>
  <%= edit_and_destroy_buttons(@brewery) %>
</div>